name: multiselect_example
description: A new Flutter project.
publish_to: none

version: 1.0.1+1  # Updated version number to reflect the upgrade

environment:
  sdk: ">=2.17.0 <4.0.0" # Updated for Dart 3 compatibility

dependencies:
  flutter:
    sdk: flutter
  flutter_multiselect:
    path: ../ # Assumes that your custom package is compatible with Flutter 3
  cupertino_icons: ^1.0.8 # Confirmed compatible with Flutter 3

flutter:
  uses-material-design: true

  # Additional asset and font configuration placeholders
