name: flutter_multiselect
description: Flutter package for multi-select UI widget, compatible with both iOS and Android, using a neutral design.
version: 1.0.1
homepage: https://github.com/hiddencaliber/flutter_multiselect

environment:
  sdk: ">=2.17.0 <4.0.0" # Updated SDK constraint for Dart 3 compatibility

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15 # Updated to latest mockito compatible with Dart 3

# Additional Flutter configurations (unchanged)
flutter:
# Asset and font instructions as placeholders
